Rework undo
streamingfast/substreams pull request #204
Opened 2023-04-06 19:00 UTC by sduchesneau

* Services for tier1 (request, response...) now exposed as `sf.substreams.rpc.v2.Stream/Blocks` and removed from `sf.substreams.v1`
  * Single module output from mapper in response. 
  * In dev mode, the additional modules output can be inspected under `debug_map_outputs` and `debug_store_outputs` 
  * The concept of "step" under blockData has been removed: reorgs are now signalled with a `BlockUndoSignal` message (without the original data)
* Services for tier2 (subrequests) now exposed as `sf.substreams.internal.v2.Substreams/ProcessRange` (not to be used externally)
* The package and modules definitions stay under `sf.substreams.v1`
* If a cursor cannot be resolved to the closest canonical parent, it will fall back to the closest final block.

2023-04-11 15:34 UTC, sduchesneau commented
```substreams run -e api-unstable.streamingfast.io:443  gs://staging.dfuseio-global.appspot.com/substreams/eth-block-meta/substreams-eth-block-meta-sync-v0.4.0.spkg  blockmeta:kv_out  --cursor=$(opaque encode c1:1:16926830:af603ab44685158e99687887c57db0081fd12476299f44ebb26f165f7739072d:16926739:2c4d685eabea79dc39be23e90f101b18713922a9e54d7fc5dc7ecf9a3eec3765) -t 16926832```
example getting out of a bad cursor ^

2023-04-11 20:24 UTC, maoueh requested changes
Main thing is around the Clock that I think should not move, there is some other stuff here and there.

2023-04-11 20:24 UTC, maoueh commented on docs/release-notes/change-log.md
> +### Highlights -- BREAKING CHANGES
We should have a section per for RPC communication and sub-section for Undo signal change. We should use a more doc-centric approach with longer description of the change, what it affects and upgrade path, we could should "trimmed down" Golang code for consuming Substreams before/after.

2023-04-11 20:24 UTC, maoueh commented on docs/release-notes/change-log.md
> +  * In dev mode, the additional modules output can be inspected under `debug_map_outputs` and `debug_store_outputs`
Single module output was already enforced but it's now removed from the protocol, we should just explained it's removal of deprecated fields, to adjust the tone a bit.

2023-04-11 20:24 UTC, maoueh commented on docs/release-notes/change-log.md
> +  * The concept of "step" under blockData has been removed: reorgs are now signalled with a `BlockUndoSignal` message (without the original data)
Would go in undo sub-section of RPC highlights with more meat about what change exactly.

2023-04-11 20:24 UTC, maoueh commented on docs/release-notes/change-log.md
> +* Services for tier2 (subrequests) now exposed as `sf.substreams.internal.v2.Substreams/ProcessRange` (not to be used externally)
I would personally talk in a dedicated operators section

2023-04-11 20:24 UTC, maoueh commented on manifest/manifest_test.go
> +	"github.com/test-go/testify/require"
Wrong test package

2023-04-11 20:24 UTC, maoueh commented on orchestrator/parallelprocessor.go
> +	_ = pbsubstreamsrpc.Request{}
Leftover?

2023-04-11 20:24 UTC, maoueh commented on client/client.go
> +	pbssinternal "github.com/streamingfast/substreams/pb/sf/substreams/intern/v2"
Not sure why we are trying to cut `al` in `intern`within `sf/substreams/intern/v2`, later we also use `pbssintern` for module and it's confusing. 

We should stick with `sf/substreams/internal/v2` and `pbssinternal`.

2023-04-11 20:24 UTC, maoueh commented on proto/sf/substreams/v1/test/test.proto
> +option go_package = "github.com/streamingfast/substreams/pb/sf/substreams/v2/test/;pbsubstreamstest";
Why changing the version here to `v2`?

2023-04-11 20:24 UTC, maoueh commented on service/tier1.go
>  	//  *
Seems to me like this was attached to `execOutWriter` code block that existed here before. Should be moved with code or removed.

2023-04-11 20:24 UTC, maoueh commented on proto/sf/substreams/rpc/v2/clock.proto
> +package sf.substreams.rpc.v2;
The `Clock` cannot moved, it's used in `substreams.yaml` as input type for some module, we must keep it under `sf.substreams.v1`

2023-04-11 20:24 UTC, maoueh commented on proto/sf/substreams/rpc/v2/service.proto
> +    BlockUndoSignal block_undo_signal = 4;
Should we think about adding `BlockFinalSignal` message right now? This could be useful for implementation where a simple "fork buffer" could be kept more easily.

We can safely add in a future update also, so maybe post-pone.

2023-04-11 20:24 UTC, maoueh commented on proto/sf/substreams/rpc/v2/service.proto
> +// on-chain. Delete that data and restart from 'last_valid_cursor'
Can you add an example using example block nums for the "flow" and what should happen when handling it.

2023-04-11 20:24 UTC, maoueh commented on proto/sf/substreams/rpc/v2/service.proto
> +// on-chain. Delete that data and restart from 'last_valid_cursor'
Should we think about adding `BlockFinalSignal` message right now? This could be useful for implementation where a simple "fork buffer" could be kept more easily.

After reading more code, it seems we have `final_block_height` within the `BlockScopedData`, so it really raise the question about `BlockFinalSignal`.

2023-04-11 20:24 UTC, maoueh commented on orchestrator/work/worker.go
> +				// respFunc(...)
What should we do with those dead code? If we keep them, they should be updated to compile with code and then we comment them out so at least they are aligned with current code.

2023-04-11 20:24 UTC, maoueh commented on orchestrator/work/worker.go
> +					&pbsubstreamsrpc.ModuleProgress{
```suggestion
					{
```

2023-04-11 20:24 UTC, maoueh commented on orchestrator/work/worker.go
> +					&pbsubstreamsrpc.ModuleProgress{
Same here 
```suggestion
					{
```

2023-04-11 20:24 UTC, maoueh commented on pipeline/outputmodules/graph.go
> +	usedModules    []*pbsubstreams.Module // all modules that need to be processed (requested directly or a required module ancestor)
Excellent renamed!

2023-04-11 20:24 UTC, maoueh commented on pipeline/outputmodules/graph.go
> +	usedModules    []*pbsubstreams.Module // all modules that need to be processed (requested directly or a required module ancestor)
Excellent rename!

2023-04-11 20:24 UTC, maoueh commented on pipeline/outputmodules/graph.go
> +func (g *Graph) AllModules() []*pbsubstreams.Module   { return g.usedModules }
Should be renamed too.

2023-04-11 20:24 UTC, maoueh commented on pipeline/outputmodules/validate.go
> +func ValidateRequest(request *pbsubstreamsrpc.Request, blockType string, isSubRequest bool) error {
`isSubRequest` is unused.

2023-04-11 20:24 UTC, maoueh commented on pipeline/outputmodules/validate.go
> +				if src.Type != blockType && src.Type != "sf.substreams.v1.Clock" {
Seems another good readon to keep the clock at `sf.substreams.v1.Clock`

2023-04-11 20:24 UTC, maoueh commented on pipeline/outputmodules/validate.go
> +func ValidateInternalRequest(request *pbssinternal.ProcessRangeRequest, blockType string) error {
You have put the non internal method directly under the Request type receiver, should we do the name here?

2023-04-11 20:24 UTC, maoueh commented on pipeline/init_test.go
> +			"sf.substreams.rpc.v2.Clock":  clockBytes,
To be reverted.

2023-04-11 20:24 UTC, maoueh commented on pipeline/pipeline.go
> +	p.forkHandler.registerUndoHandler(func(clock *pbsubstreamsrpc.Clock, moduleOutputs []*pbssinternal.ModuleOutput) {
`clock` is not used anymore, should the undo handler be modified?

2023-04-11 20:24 UTC, maoueh commented on pipeline/pipeline.go
> +	if err := respFunc(substreams.NewBlockDataResponse(out)); err != nil {
Not sure why we renamed, maybe you would like to have `BlockData` instead in the Proto def :)?

2023-04-11 20:24 UTC, maoueh commented on pipeline/process_block.go
> +		// Timestamp: timestamppb.New(block.Time()),
Hmmm, this makes me wonder that maybe we should use `BlockRef` instead of `Clock` in the RPC layer where this is used, maybe just in the `undo` case. If we are not able to use the `Timestamp` everywhere, we need to seriously think about using a different type.

2023-04-11 20:24 UTC, maoueh commented on pipeline/process_block.go
> +		})
```suggestion
	return p.respFunc(
		&pbsubstreamsrpc.Response{
			Message: &pbsubstreamsrpc.Response_BlockUndoSignal{
				BlockUndoSignal: &pbsubstreamsrpc.BlockUndoSignal{
					LastValidClock:  targetClock,
					LastValidCursor: targetCursor.ToOpaque(),
				},
			},
		})
```

2023-04-11 20:24 UTC, maoueh commented on pipeline/process_block.go
> +				return fmt.Errorf("failed to run pre-first-block-data-hook: %w", err)
```suggestion
				return fmt.Errorf("failed to run pre first block data hook: %w", err)
```

I think we are safe to use the spaced version.

2023-04-11 20:24 UTC, maoueh commented on pipeline/process_block.go
> +		p.preFirstBlockDataHooks = nil
I'm a bit skeptical about using this to use it as the "first has been executed" way of things.

2023-04-11 20:24 UTC, maoueh commented on pipeline/resolve.go
> +		req.StartCursor = ""
Are we loosing some "visibility" on the real actual request by doing this? Could we instead find a way to keep the request StartCursor but use a "resolvedCursor"?

2023-04-11 20:24 UTC, maoueh commented on pipeline/resolve.go
> +		return 0, nil, status.Errorf(grpccodes.InvalidArgument, "cannot resolve startCursor %q: %s", cursor, err.Error())
In the other cursor related error, we use `start cursor`, I would be in favor of doing this instead:
```suggestion
		return 0, nil, status.Errorf(grpccodes.InvalidArgument, "cannot resolve StartCursor %q: %s", cursor, err.Error())
```

And normalize the other one above. This way, the user see immediately which field is the problem.

2023-04-11 20:24 UTC, maoueh commented on pipeline/resolve.go
> +		req.StartCursor = validCursor.ToOpaque()
Same thing here about modified the origin request.

2023-04-11 20:24 UTC, maoueh commented on pipeline/resolve.go
> +		if src == nil {
`src` cannot be `nil` here, the previous condition force it to be `non-nil`.

2023-04-11 20:24 UTC, maoueh commented on pipeline/resolve.go
> +		if src == nil {
I verified, `NewFileSourceFromCursor` seems it cannot return `nil`.

2023-04-11 20:24 UTC, maoueh commented on pipeline/resolve_test.go
> +			name: "step undo", // substreams customers should not receive these cursors now, kept for backwards compatibility
I'm not sure what backward compatibility we are keeping here.

2023-04-11 20:24 UTC, maoueh commented on service/tier2.go
> +	//ctx = tracking.WithBytesMeter(ctx, bytesMeter)
To be updated?

2023-04-11 20:24 UTC, maoueh commented on service/tier1.go
>  	//  *
Seems that it should be deleted because it's now in `Tier2Service`

2023-04-11 20:24 UTC, maoueh commented on storage/store/value_get.go
> +			panic(fmt.Sprintf("invalid value %q for pbsspriv.StateDelta::Op for key %q", delta.Operation, delta.Key))
All occurrences of `pbsspriv` should become `pbssinternal`

2023-04-11 20:24 UTC, maoueh requested changes
Main thing is around the Clock that I think should not move, there is some other stuff here and there.

2023-04-11 20:24 UTC, maoueh requested changes
Main thing is around the Clock that I think should not move, there is some other stuff here and there.

2023-04-12 18:28 UTC, maoueh approved these changes

2023-04-12 18:28 UTC, maoueh commented on docs/release-notes/change-log.md
> +* Deprecating the "Request" and "Response" messages, with some others, from `sf.substreams.v1`, now that they moved to `sf.substreams.rpc.v2`
Deprecating or removing?

2023-04-12 18:56 UTC, merged