Add cookbook patterns
streamingfast/substreams pull request #245
Opened 2023-07-05 23:31 UTC by YaroShkvorets

Add patterns to cookbook:

  * Dynamic data sources
  * Factory parameterization
  * Advanced parameters
  * Keys in stores
  * Aggregation windows
  * Subgraph entity changes

2023-07-06 01:13 UTC, maoueh requested changes
Small suggestions here and there, can be batched added and committed straight on this PR

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/dynamic-data-sources.md
> +description: Dynamic data sources and substreams
```suggestion
description: Dynamic data sources and Substreams
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/dynamic-data-sources.md
> +# Dynamic data sources and substreams
```suggestion
# Dynamic data sources and Substreams
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/dynamic-data-sources.md
> +Here's how you can achieve that with substreams.
```suggestion
Here's how you can achieve that with Substreams.
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/dynamic-data-sources.md
> +We'll be using UniswapV3 example where the Factory creates and deploys its smart contract for each pool.
```suggestion
We'll be using Uniswap V3 example where the Factory creates and deploys its smart contract for each pool.
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/dynamic-data-sources.md
> +We can now take that map module output and direct these pool creation events into a substreams key-value store using a store module:
```suggestion
We can now take that map module output and direct these pool creation events into a Substreams key-value store using a store module:
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/dynamic-data-sources.md
> +Alternatively, we could make RPC calls to get the pool details from an RPC node but that would be extremely inefficient considering that we would need to make RPC calls for Millions of such events. U
```suggestion
Alternatively, we could make RPC calls to get the pool details from an RPC node but that would be extremely inefficient considering that we would need to make RPC calls for millions of such events. Using a store will be much faster.
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/dynamic-data-sources.md
> +For a real-life application of this pattern see [Uniswap V3 substream](https://github.com/streamingfast/substreams-uniswap-v3)
```suggestion
For a real-life application of this pattern see [Uniswap V3 Substreams](https://github.com/streamingfast/substreams-uniswap-v3)
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/dynamic-data-sources.md
> +* [Substreams Entity Changes](https://github.com/streamingfast/substreams-sink-entity-changes)
```suggestion
* [Substreams Sink Entity Changes](https://github.com/streamingfast/substreams-sink-entity-changes)
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/entity-changes.md
> +A common convention for substreams-powered subgraph development is to implement a `graph_out` module emitting `EntityChanges` events. When these events are consumed by the indexer, entities in the su
```suggestion
A common convention for Substreams-powered subgraph development is to implement a `graph_out` module emitting `sf.substreams.sink.entity.v1.EntityChanges` events. When these events are consumed by the indexer, entities in the subgraph are updated accordingly.
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/entity-changes.md
> +      type: proto:substreams.entity.v1.EntityChanges
```suggestion
      type: proto:sf.substreams.sink.entity.v1.EntityChanges
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/entity-changes.md
> +            .set("ethPriceUSD", &BigDecimal::zero());
```suggestion
            .set("ethPriceUSD", BigDecimal::zero());
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/entity-changes.md
> +    for delta in derived_eth_prices_deltas.deltas.iter(){
```suggestion
    for delta in derived_eth_prices_deltas.into_iter(){
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/entity-changes.md
> +        tables.update_row("Bundle", "1").set("ethPriceUSD", &delta.new_value);
```suggestion
        tables.update_row("Bundle", "1").set("ethPriceUSD", delta.new_value);
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/entity-changes.md
> +`substreams-entity-change` crate offers `Table` struct to work with the entities.
```suggestion
`substreams-entity-change` crate offers `Tables` struct to work with the entities.
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/entity-changes.md
> +        .set("ethPriceUSD", &BigDecimal::zero());
```suggestion
        .set("ethPriceUSD", BigDecimal::zero());
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/entity-changes.md
> +`create_row` takes two arguments - Table name and row id. In our case, we use "Bundle" entity name - that's the entity we have defined in the subgraph `schema.graphql` schema. We use "1" as `id`. Tha
```suggestion
`create_row` takes two arguments: entity name and entity id. In our case, we use "Bundle" entity name - that's the entity we have defined in the subgraph `schema.graphql` schema. We use "1" as `id`. That's the only price that we will have.
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/entity-changes.md
> +for delta in derived_eth_prices_deltas.deltas.iter(){
```suggestion
for delta in derived_eth_prices_deltas.into_iter(){
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/entity-changes.md
> +        .set("ethPriceUSD", &delta.new_value);
```suggestion
        .set("ethPriceUSD", delta.new_value);
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/entity-changes.md
> +Here, we use `update_row` method to create an UPDATE entity operation, and we use `set` method to set the corresponding entity field.
```suggestion
Here, we use `update_row` method to create an `UPDATE` entity operation, and we use `set` method to set the corresponding entity field.
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/factory-params.md
> +Instead of hard-coding the address in the substreams binary, you can customize it without having to rebuild or even repackage the substreams package. The consumer can then just provide the address as
```suggestion
Instead of hard-coding the address in the Substreams binary, you can customize it without having to rebuild or even repackage the Substreams package. The consumer can then just provide the address as a parameter.
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/keys-in-stores.md
> +In most cases, you will encode data into your keys into segmented parts, adding a prefix as namespace for example `user` and `<address>` joined together using a separator.  Segments in a key are conv
```suggestion
In most cases, you will encode data into your keys into segmented parts, adding a prefix as namespace for example `user` and `<address>` joined together using a separator.  Segments in a key are conventionally joined with `:` as a separator.
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/keys-in-stores.md
> +* [Key module source code](https://github.com/streamingfast/substreams-rs/blob/develop/substreams/src/key.rs)
Maybe we should link to the `docs.rs` site instead?

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/keys-in-stores.md
> +For a full example see [Uniswap V3 substreams](https://github.com/streamingfast/substreams-uniswap-v3/blob/ca90fe3908a76905b43e05f0522e1e9338d88972/src/lib.rs#L1139-L1163)
```suggestion
For a full example see [Uniswap V3 Substreams](https://github.com/streamingfast/substreams-uniswap-v3/blob/ca90fe3908a76905b43e05f0522e1e9338d88972/src/lib.rs#L1139-L1163)
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/aggregation-windows.md
> +Store module key-value storage can hold at most 1GB. It is usually enough if used correctly, but it is still a good idea (and sometimes even necessary) to free up unused keys. It is especially true f
```suggestion
Store module key-value storage can hold at most 1 GiB. It is usually enough if used correctly, but it is still a good idea (and sometimes even necessary) to free up unused keys. It is especially true for cases where you work with aggregation windows.
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/factory-params.md
> +When running substreams for a dApp, you need to know the smart contract deployment address and for obvious reasons, this address will be different for each deployment.
```suggestion
When running Substreams for a dApp, you need to know the smart contract deployment address and for obvious reasons, this address will be different for each deployment.
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook/factory-params.md
> +To pass the parameter to the module using substreams CLI you can use `-p` key:
```suggestion
To pass the parameter to the module using `substreams` CLI you can use `-p` key:
```

2023-07-06 01:13 UTC, maoueh commented on docs/developers-guide/cookbook.md
> +Most of the patterns are based on Uniswap V3 substreams.
```suggestion
Most of the patterns are based on Uniswap V3 Substreams.
```

2023-07-06 20:35 UTC, YaroShkvorets commented on docs/developers-guide/cookbook/keys-in-stores.md
> +* [Key module source code](https://github.com/streamingfast/substreams-rs/blob/develop/substreams/src/key.rs)
Changed to docs.rs: https://docs.rs/substreams/latest/substreams/key/index.html

2023-07-07 12:02 UTC, abourget commented
Are we good? I'd love to merge this :)

2023-07-07 14:22 UTC, YaroShkvorets commented
I'm good to merge.

2023-07-07 16:18 UTC, matthewdarwin commented
@maoueh any further comments?

2023-07-07 16:36 UTC, merged