New Docs
streamingfast/substreams pull request #343
Opened 2023-11-27 01:25 UTC by enoldev

2023-12-01 20:26 UTC, mdimercurio requested changes

2023-12-01 20:26 UTC, mdimercurio commented on docs/README.md
>  description: StreamingFast Substreams documentation
we might not need a documentation here as the title already mentions "Substreams", it seems a bit repetitive
<img width="440" alt="image" src="https://github.com/streamingfast/substreams/assets/4933447/34da2db8-fe7d-4e92-bc73-112e0571d738">

2023-12-01 20:26 UTC, mdimercurio commented on docs/README.md
> +**In order to define which specific data you want to extract from the blockchain, you can use Substreams packages**. For example, consider that you want to retrieve data from the Uniswap v3 smart con
```suggestion
**Uou can use Substreams packages to define which specific data you want to extract from the blockchain**. For example, consider that you want to retrieve data from the Uniswap v3 smart contract. You can simply use the [Uniswap v3 Substreams Package](https://substreams.dev/streamingfast/uniswap-v3/v0.2.7) and send that data wherever you want!
```

2023-12-01 20:26 UTC, mdimercurio commented on docs/README.md
> +There are many ready-to-use Substreams packages, so you can simply consume them. Use the **Substreams Registry ([https://substreams.dev](https://substreams.dev)) to explore packages**.
```suggestion
There are many ready-to-use Substreams packages, so you can simply consume them. Use the **[Substreams.dev Registry](https://substreams.dev) to explore packages**.
```

2023-12-01 20:26 UTC, mdimercurio commented on docs/README.md
> +{% embed url="https://www.youtube.com/watch?v=gVqGCqKVM08" %}
there's something weird with the video. When listening with my headset, the sound only comes from the left ear

2023-12-01 20:26 UTC, mdimercurio commented on docs/README.md
> +{% endembed %}
I'd add a text version at the bottom for folks that don't want to check the video.  Adding the sample code

2023-12-01 20:26 UTC, mdimercurio commented on docs/README.md
> +Substreams is a technology that allows you to **extract blockchain data in a fast and reliable way!**
I like the way Substreams is positioned in the glossary, we should include some of that content here

2023-12-01 20:26 UTC, mdimercurio commented on docs/new/develop/architecture.md
> +description: Lenar about the Substreams architecture
```suggestion
description: Learn about the Substreams architecture
```

2023-12-01 20:26 UTC, mdimercurio commented on docs/new/develop/architecture.md
> +---
on the site, this renders as the home page: https://substreams.streamingfast.io/~/revisions/7wlUfBToYnQ1WnIvo7uu/documentation/introduction-1/architecture

2023-12-01 20:26 UTC, mdimercurio commented on docs/new/develop/architecture.md
> +Forward parallel execution only occurs in production mode.
this doc seems very detailed for an "Architecture" doc. I'd expect a diagram of the components and definition of their role

2023-12-01 20:26 UTC, mdimercurio commented on docs/SUMMARY.md
>  * [Examples](reference-and-specs/examples.md)
I'd try to make these examples more visible, maybe adding a link on the home page

2023-12-03 16:09 UTC, enoldev commented on docs/README.md
> +{% endembed %}
I've included the text version in the "Develop Substreams". I'd like to keep the landing page as short as possible, so we don't stress new users

2024-01-18 18:00 UTC, merged